### ISSUE TITLE
Election: CPC Secondary Director

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1142]
This Issue tracks the election of the CPC Secondary Director / At Large Community director.  Details about the role can be found in the [CPC charter](https://github.com/openjs-foundation/cross-project-council/blob/HEAD/CPC-CHARTER.md#the-secondary-cpc-director-as-defined-in-43e-in-the-openjs-foundation-bylaws).

### Nomination Process
Please complete [this form](https://forms.gle/v3gygb88W94zQDBQ7).

### Eligibility
Nominees for this role must be an [Active OpenJS Collaborator](https://github.com/openjs-foundation/cross-project-council/blob/HEAD/governance/GOVERNANCE.md#definition-of-an-active-openjs-collaborator) at the time of their selection, as defined in the CPC's Governance document.

### Term
Term begins Sept. 1, 2023 and concludes Aug. 31, 2024.

```[tasklist]
### Election Schedule
- [x] Nomination Period August 14-25
- [x] Voting Period Via Opavote August 28-Sept 1
- [x] Announcement of Election Winners September 4th
```

**Comment by bensternthal** [comment]
@mcollina I saw your note in the other issue about running for re-election. Please make sure to self nominate using [this form](https://forms.gle/v3gygb88W94zQDBQ7).

**Comment by bensternthal** [comment]
Per Friday's board vote approving an additional director, we are extending the deadline on the nomination period one week, to August 25th. This vote will elect two board seats.

**Comment by bensternthal** [comment]
Actually scratch that, we should not open up the additional seat until the by-laws are published AND the updated CPC charter is published.  Will still move the nomination period out one week to give folks extra time to nominate (it's vacation season).

**Comment by joesepi** [comment]
@bensternthal - Do we need to update the voting period and announcement dates to reflect the extension?

**Comment by bensternthal** [comment]
Good call, adjusted. I am hoping to do the vote in 1 week.

**Comment by bensternthal** [comment]
Ballots have been sent out to voting members via Opavote. If anyone has not received an email from Opavote and believes this to be an error, please contact me.

**Comment by Trott** [comment]
In my role as a Node.js representative on the CPC, should my vote represent my personal assessment or should it represent the  view of the TSC of Node.js collectively? Or is that a question for me to take up with the TSC?

**Comment by bensternthal** [comment]
@Trott this isn't addressed (as far as I can tell) in the CPC documentation. I would suggest working with the TSC to decide.

**Comment by tobie** [comment]
That's an interesting question. There's nothing in the bylaws, the CPC charter, governance or member expectations documents that point in either direction.

Given the vote is secret and that there are no distinction made between voting members in the charter, regardless of how they get elected, it feels reasonable to assume every voting member has been delegated decision-making power within the CPC. If not, CPC voting members elected by At Large projects and by other CPC members should be having conversations with At Large project maintainers and every CPC member respectively before casting a vote, and we'd be spending even more of our time doing election work rather than work that actually benefits the different constituencies we represent.

Additionally, as a voting member, you have a lot more visibility in how the candidates actually operate in the CPC and Board than the folks that elected you have, and so you're better positioned to make the right call.

However there might be circumstances where you'd like the opinion of the Node TSC, or someone else for that matter, and you should absolutely seek it, but it shouldn't be a requirement.
