### ISSUE TITLE
Revisit & Decide On Primary Goal Of Travel Fund

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1188]
Before we create a new process for intaking and evaluating travel fund requests, we want to ensure that the primary goal of the travel fund is still correct. If we align on a primary goal we can move forward with strategy and tactics.

The next steps after we align on the goal will be:

1. Decide on budgeting e.g., quarterly/per event etc
2. Decide on the approval method and cadence

Note we have a lot of thinking already done on the above, so we are close... we just need to push forward on consensus. 

### Current Stated Goal (See [original](https://github.com/openjs-foundation/community-fund/blob/main/programs/travel-fund/README.md#travel-fund ))

This fund exists to support individuals who may not otherwise have the opportunity to attend in three categories.

- Collaborators
- Standards Participation
- Diversity, Equity and Inclusion

The fund can cover the costs, in whole or in part, of a participant's hotel, airfare, and some event registrations. Fund Applicants should seek to use employer funds as a first resort. Need is a factor.

###  Proposed Goal For 2024

This fund supports travel and attendance at events and activities directly related to OpenJS projects, technologies, or goals. We support travel for individuals who are:

- Collaborators
- Standards body participants
- Speakers

The fund can cover the costs, in whole or in part, of a participant's hotel, airfare, and some event registrations. Fund applicants should seek to use employer funds as a first resort.

**Comment by mhdawson** [comment]
> Speakers 

I think this could use a bit more clarification. I think in the past we would support collaborators from projects to speak and spread the word about those projects. Is this intended to be speakers who are not contributors/collaborators to one of the Foundation projects?

**Comment by mhdawson** [comment]
Is there intended to be some priority implied by the order of the list?  I would prioritize bringing collaborators together to be able to have in-person collaboration versus brining speakers to an OpenJS even that don't have any other existing connection to Foundation projects.

**Comment by eemeli** [comment]
Why are the costs of speakers at OpenJS events not considered as a part of the event's budget?

**Comment by joesepi** [comment]
> Why are the costs of speakers at OpenJS events not considered as a part of the event's budget?

I dont see where it says we should pay OpenJS Event speakers with community fund.

> I think this could use a bit more clarification. I think in the past we would support collaborators from projects to speak and spread the word about those projects. Is this intended to be speakers who are not contributors/collaborators to one of the Foundation projects?

We tried to address this question with the phrase "events and activities directly related to OpenJS projects, technologies, or goals"

> Is there intended to be some priority implied by the order of the list?

There was no priority implied in the list, however, I have edited the list to put speakers last on that list because I agree that the other two may be a higher priority but that is up for debate..... but that is not to debate now...

The plan for this work is to:
1. Set goals
2. Set strategy
3. Define tactics

We are still at the goals part of this process. Let's stay focused on that for this issue to avoid noise and churn, please.

**Comment by PaulaPaul** [comment]
For reference @bensternthal and @joesepi this is the information on what the Linux Foundation publishes on ther DEI efforts: [DEI at LF Events](https://www.linuxfoundation.org/about/diversity-and-inclusion-at-our-events#:~:text=All%20of%20our%20events%20are,%2C%20and%20most%20importantly%2C%20people.)

I've also commented on [issue 1197](https://github.com/openjs-foundation/cross-project-council/issues/1197) opened by @tobie with information about the difference between Affirmative Action (and the US court ruling) and DEI programs, neither of which are illegal. 

I believe the Foundation should have a DEI program, even if it merely consists of the travel budget for events and alignment with the DEI statements about events from the LF (which include event scholarships related to DEI).

Since having a DEI program (or not) is a strategic decision for the Foundation, would the CPC benefit from input from the Board? If so, can I help facilitate that?

**Comment by tobie** [comment]
I agree with @PaulaPaul, here. think it would be useful to have a better understanding of the legal advice the foundation has received on this topic and get the Board involved.

Indeed, the CPC had made DEI one of the pillars of how this fund was to be used, and this has received support on numerous occasions. Moving away from explicitly supporting this goal shouldn't be considered lightly and should require a formal process:

1. The Board should be briefed on the legal considerations and recommendation to move away from explicitly supporting DEI with this fund.
2. The Board should consider the counsel's recommendation and make its own risk assessment.
3. If the Board comes to the conclusion that the CPC must redirect this fund away from explicit DEI support, it should then communicate this to the CPC, and provide guidance as to what the CPC is allowed to do with this fund (and what information it is OK to collect).

**Comment by rginn** [comment]
We just concluded a CPC working session. It turns out that folks were conflating data collection with diversity. We are solving the data collection issue with LF policy as our guide. (Note: We will be able to collect enough information for diversity.) We are adding diversity back as one of the primary goals of the Community Fund.

**Comment by tobie** [comment]
As @rginn mentioned above and as we discussed in our working session, we'll be able to continue gathering necessary information to support our DEI effort with this fund. @bensternthal and @rginn will be looking into what information can be safely collected. It's worth noting that the LF is still collecting diversity-related data for speakers and only dropped its collection of data for attendees. See the questions asked when submitting a talk below:

<img width="625" alt="screenshot of the speaker intake formula. The text reads: 'The Linux Foundation is committed to a diverse and inclusive community. The following optional questions are asked in an effort to track our progress in increasing diversity at events and will remain confidential.' It includes three drop-down form inputs titled: 'Gender identity', 'Person of color', and 'Identify with other underrepresented group(s)'" src="https://github.com/openjs-foundation/cross-project-council/assets/3392/19545e1f-6fb0-4831-88f9-cb0e83a615cc">

So we can expect to at least be able to collect that kind of data.

If my understanding is correct, inability to collect meaningfully diversity data was the driver behind these proposed changes to the fund's goals. Given that this is no longer an issue _and given the real DEI challenges our industry continues to face_, I think we should just close this issue.

**Comment by tobie** [comment]
Agreement to close it in the November 14, CPC meeting.
