### ISSUE TITLE
Agenda item - Collab Summit Session for the CPC?

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#125]
In the collaborator summit planning meeting today, we discussed whether we need to save a spot in the schedule for a CPC meeting or session. Let's take ~5-10 to discuss on Monday's call?

**Comment by mcollina** [comment]
I think it’s a great idea. In the history of the TSC we restrained from doing so because most of us where involved in other sessions, and we prefer to keep things offline for the TSC.

What will be the agenda? I think it could be a good moment to present the CPC/charter/processes etc to most of the projects, and get us to know better.

**Comment by jorydotcom** [comment]
RE the agenda; great question... I figured that would be up for discussion. I'm just imagining it would be highly valuable to convene the CPC when so many folks would be able to participate, having set aside the time and place 😄

**Comment by jorydotcom** [comment]
Just wanted to capture that this session was submitted to the collab summit

**Comment by trivikr** [comment]
Time: **CEST Thu 30-May-2019 12:00 (12:00 PM)**
Zoom link: https://zoom.us/j/381668642

**Comment by jorydotcom** [comment]
closing this issue as the summit has concluded <3 thanks all!
