### ISSUE TITLE
Nominating Chair and Director

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/cross-project-council#179]
Hey All,

Now that you are officially bootstrapped it is time to nominate a chair + director as outlined in [The Charter](https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#section-7-elections)

Keep in mind that we can always amend the charter (with board approval) if folks are not happy with current process

**Comment by mcollina** [comment]
I think we should start collecting nominees! Any volunteer?

**Comment by kborchers** [comment]
Are we wanting this to be one person or two? The charter allows either way.

I'm happy to throw my name in for Director having served on boards in the past and also worked with many on the current board while with the JSF. If we want this person to be Director and Chair, I'd be happy to do that as well but attendance at every meeting might be difficult due to work/work travel schedules as this would mostly be out of my personal time and not work time.

**Comment by ryanblock** [comment]
Unclear from the charter whether such nominations follow Robert’s Rules, but all the same I’d like to second the nomination for @kborchers!

**Comment by MylesBorins** [comment]
The duties of chair and director are different enough that there isn't a
huge benefit to it being a single person.

Directors should expect a commitment of 2-5 hours a week of work.

**Comment by brianwarner** [comment]
As discussed in the initial CPC meeting just now, the initial process for receiving nominations will be:
 * Send nominations directly to operations@openjsf.org (forwards to the OpenJS Foundation program manager, in this case, Brian).
 * Brian will keep the nominations private during the nomination period.
 * When the nomination period is closed, Brian will post all notifications for review.

**Comment by MylesBorins** [comment]
We have our official Reps

@kborchers is our CPC Director and @joesepi is our CPC Chair
