### ISSUE TITLE
Can we get an update on the Node.js Certification program?

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#192]
A couple people have reached out to me with regards to the current status of this program. Perhaps we can use this issue as an opportunity to give a public update from either the board or the Linux foundation folks? I'll start by asking @brianwarner who I believe can shine some light here.

Thanks!

**Comment by brianwarner** [comment]
Yep, I can help with this.  We're in the final stages of getting the certification program launched, debugging the questions and ensuring they work well with the TrueAbility platform.  With the obvious caveats about unexpected surprises and a sincere hope that I don't jinx us by saying this aloud, we are on track to announce the specific details and first available testing dates in the next two months.

Here's what's happening in the meantime.

After we finish debugging, we'll enter alpha testing.  Alpha testers are exposed to a broad cross-section of the exam, and are not eligible for certification on this version of the exam due to their deep levels of access.  The goal of this phase is to flush out any corner cases which weren't caught during development.

Then comes beta testing.  Beta testers take the exam under normal candidate circumstances (generally at a discount).  The beta testers' performance will help establish an appropriate pass/fail threshold.  Once those thresholds have been set, beta testers who met the passing criteria will receive the certification retroactively.

After this point, the exam becomes generally available, and candidates can schedule exams at their convenience.  Again, timeline caveats apply, but we hope to start offering exams around the end of this summer.

**Comment by jhonyourangel** [comment]
Thank you.
Looking forward.

**Comment by MylesBorins** [comment]
Closing as update was given

**Comment by lavnishl** [comment]
Looking forward for any updates on this ?
