### ISSUE TITLE
Create page with links to slack channels and sign up link on OpenJSF.org/slack

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#260]

**Comment by brianwarner** [comment]
Here's a page to get started.  We can add more content and links to it as needed.

In addition to the Slack links, it also provides a navigational path from the website back to this repo, and points to the mailing lists.

https://openjsf.org/collaboration/

**Comment by mhdawson** [comment]
Looks good.  One additional suggestion is that under the `Slack` entry we list out the channels and what they are intended for, possibly with some links to repos etc. For example, the #standards one should probably have a link to https://github.com/openjs-foundation/standards

**Comment by brianwarner** [comment]
Certainly, I can list out the channels.  For the repos etc, would it make more sense to have that info in a pinned post in each channel, so that I'm not in the critical path if someone wants to update it?

In general, it would probably be a good idea to have such stuff pinned in the channels.  For example, meeting times and connection info, links to repos, etc.

**Comment by brianwarner** [comment]
I was just looking into this after someone mentioned it in the meeting, GreetBot would be a good option.  It can greet people in DMs when they join #general.  Thoughts?

**Comment by brianwarner** [comment]
Also, I've updated the collaboration page with the links, per the discussion in the meeting.  I also fleshed out a few other places.

**Comment by kborchers** [comment]
@brianwarner I am +1 for GreetBot.

1 other item I noticed on that page is that the Google calendar isn't easy to find since it is "hidden" under the GitHub section and only mentions that it is a CPC meeting schedule but it also has the Standards WG meetings on it and will likely have other events added in the future. Could you Add a section after GitHub called Calendar or something like that with a 1-2 sentence intro about the OpenJS Foundation Google calendar and maybe a list of meetings/events it will track (currently CPC meetings and Standards WG meetings) and then maybe remove that CPC-specific bullet from the GitHub section?

**Comment by brianwarner** [comment]
@kborchers - certainly, adding an explicit Calendar section makes sense to me.

Also, good point that the calendar has meetings from multiple working groups on it.  Instead of removing it from the CPC section, can I suggest instead that links be added to all of the others?  That makes it abundantly clear how to find the meeting times (and a few extra links do no harm).

Also, duly noted on GreetBot.  Unless someone chimes in with concerns, I'll get it going in a day or two.

**Comment by kborchers** [comment]
> Instead of removing it from the CPC section, can I suggest instead that links be added to all of the others?

👍

**Comment by joesepi** [comment]
Thanks @brianwarner

**Comment by joesepi** [comment]
I believe this issue is resolved by the addition and tweaking of this page:
https://openjsf.org/collaboration/

I created an issue specifically for the Greetbot addition to Slack: #277
