### ISSUE TITLE
Duplicate onboarding checklist

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#288]
There's an onboarding checklist at the bottom of [NEW_PROJECT_APPLICATION.md](https://github.com/openjs-foundation/cross-project-council/blob/master/NEW_PROJECT_APPLICATION.md#onboarding-checklist) and one as an [issue template](https://github.com/openjs-foundation/cross-project-council/blob/master/.github/ISSUE_TEMPLATE/project-onboarding-checklist-template.md). Would you take a PR that referenced the latter in NEW_PROJECT_APPLICATION.md instead of keeping two copies around which _will_ get out of sync?

**Comment by jorydotcom** [comment]
@tobie At the moment I'm glad to have the checklist included in the issue template because we're also putting existing projects through the process and it's helpful to see the status of the checklist for a given project right there on the issue. But we can def. discuss at the CPC meeting today & see if there are some other optimizations / adjustments to make. I don't think the issue template is necessarily the right format long term, for example

**Comment by tobie** [comment]
Fair enough, though I think not being sure _where_ the checklist ends-up (and being open to moving it at a later stage) is a different concern than avoiding to create two, potentially out of sync checklists.

**Comment by tobie** [comment]
Lurking on the conf call, I think there is a misunderstanding between us, @jorydotcom.My concern is about a duplicate checklist between the NEW_PROJECT_APPLICATION.md file and the ISSUE_TEMPLATE/project-onboarding-checklist-template.md file. Adding the checklist to each issue created is perfectly fine. It's the whole point!

**Comment by MylesBorins** [comment]
I've opened a PR that should remove the duplication
