### ISSUE TITLE
Sole-maintainer projects

### ISSUE THREAD

**Issue by mcollina** [openjs-foundation/cross-project-council#298]
I think we should recommend that a project have at least 2 or 3 active maintainers before bringing them into the Foundation. I'm not convinced that a project with a single collaborator is good for either the project of the Foundation.

wdyt?

**Comment by dylans** [comment]
I agree. It does remind me that perhaps there is more we can do to help aspiring foundation projects.

Perhaps we could put together a guide or blog somewhere with our recommendations on how to create a healthy open source project and community, and point to this as part of the criteria for the foundation. I mention this because most or all of us here have been through this before, but a lot of applicants may be working on their first open source project and not understand why we have the criteria we have.

I know we have some of this specifically around applying to become a foundation project in places such as https://github.com/openjs-foundation/cross-project-council/blob/master/PROJECT_PROGRESSION.md and https://github.com/openjs-foundation/cross-project-council/blob/master/NEW_PROJECT_APPLICATION.md#onboarding-checklist, but perhaps a less foundation-centric guide would help new projects understand what they should do an why to create a healthy open source project, perhaps in preparation for joining the foundation. And if the guide is solid, it could also be useful in raising awareness for the foundation.

**Comment by mcollina** [comment]
I totally agree.

I’d also like to make the requirement of 2 collaborators (or maybe 3) as a requirement for joining the Foundation, and maybe to all projects.

**Comment by christian-bromann** [comment]
> I’d also like to make the requirement of 2 collaborators (or maybe 3) as a requirement

@mcollina how do you define collaborators here? When do you qualify as a collaborator? Is it based on recent contributions or is some metric in overall contribution sufficient?

**Comment by mcollina** [comment]
> @mcollina how do you define collaborators here? When do you qualify as a collaborator? Is it based on recent contributions or is some metric in overall contribution sufficient?

People with commit/triage/whatever access to the project, not "pass by" contributions.

**Comment by bd82** [comment]
> People with commit/triage/whatever access to the project, not "pass by" contributions.

This does not describe the "active" part well, What if a project has 5 persons with write access to the project, but 4 of those had **no** activity in the last year? does it meet the criteria? 

Is the policy attempting to avoid loss of admin access to a project/org if the sole maintainer gets run over by a bus or is attempting to avoid a project dying off due to a bus factor of 1?

**Comment by mcollina** [comment]
> is attempting to avoid a project dying off due to a bus factor of 1?

This ^.

**Comment by brianwarner** [comment]
Addressing the bus factor, would it be wise to have a neutral person/account with owner-level access?  This is something I can set up, if need be.

**Comment by timmywil** [comment]
I agree with the sentiment, but I think a recommendation is better than a requirement. Each project can be discussed on a case-by-case basis. Besides, a lack of active contributors may be one of the reasons a project wants to join the foundation, seeking help in maintenance. I’m sure we’ve all seen projects that are important and useful that unfortunately lacks active contributors.

**Comment by bd82** [comment]
In terms of project's health:
Does it significantly matter if a project has multiple "active maintainers" **if** the vast majority of the commits are done by a **single "main" maintainer**? 

Just because there are multiple active maintainers does not mean the bus factor is not still effectively 1 (or very close to it).

For example many very popular projects are effectively one person's passion who does most of the actual commits and that person not be easily replaceable (Be it due to time/priority/domain expertise/interest) even if there are other "active maintainers".

Examples of some  (very popular and useful) JSF projects that exhibit the **"main maintainer" pattern.**
- [Express](https://github.com/expressjs/express/graphs/contributors)
- [Esprima](https://github.com/jquery/esprima/graphs/contributors)
- [Lodash](https://github.com/lodash/lodash/graphs/contributors)
- [Webpack](https://github.com/webpack/webpack/graphs/contributors)

Note that some of these projects "changed" the identify of the main maintainer at some point
in their history, but it seems like a **new** main maintainer joined rather than an "active maintainer" transitioned into the main maintainer role...

I think this is part of the general problem of open source sustainability,  There is probably a strong correlation between projects with a high bus factor and those that have strong corporate sponsorship.

For Example, these contribution graphs seem much more likely to survive a random meteor strike. 😄 
- [Microsoft's TypeScript](https://github.com/microsoft/TypeScript/graphs/contributors)
- [Microsoft's VSCode](https://github.com/microsoft/vscode/graphs/contributo)
- [FaceBook's React](https://github.com/facebook/react/graphs/contributors) 
- [Google's Guava](https://github.com/google/guava/graphs/contributors)

But the "High Bus Factor" goal does not seem to be achievable by many very popular and useful OSS projects, so perhaps it is a too high bar to be mandatory...

Should it perhaps be mandatory in order for projects to move to the impact stage?

**Comment by ljharb** [comment]
I disagree strongly with this; often the whole point of entering the foundation is to get more maintainers. Additionally, as was pointed out, what’s important is multiple active maintainers, and that’s a much much harder thing to quantity anyways.

For example, i am the sole active maintainer by my estimation on many projects for which there are other maintainers, officially - how would you quantify those?

**Comment by MylesBorins** [comment]
While having a sole maintainer could be a signal that a project may not be suitable for our foundation I don't think it would be fair to call it the only signal that we rely on to accept or decline a project. If a project currently has a single maintainer, actively wants to get more through the "growth" phase, and is an extremely relevant project why wouldn't we want to accept them?

If a project has a single maintainer and barely any ecosystem usage, that is a completely different story.

To me this seems like one signal of many that we should be looking at.

That being said, perhaps a scoring rubric could help us fairly apply acceptance criteria across various projects.

**Comment by dmethvin** [comment]
Scoring systems are tough to calibrate without a bunch of test cases, keep that in mind. 

I think that by itself, a project with just one maintainer is not disqualifying. As @timmywil said, that may be why they're applying. It's definitely something that needs to be addressed for graduation, and we should have a plan for how that can happen. (Hope is not a strategy.)

**Comment by mhdawson** [comment]
We might put together a list of qualities for an "ideal" candidate.  Lack of any one of them would not be a disqualifier but it would still give candidates some idea as to how to judge if there is a good fit...

**Comment by wesleytodd** [comment]
> a lack of active contributors may be one of the reasons a project wants to join the foundation

I think that this is only one small reason to join the foundation.  Getting support so that the maintainers need to do less non-dev work is more important.  For example: setting up CoC or governance doc, IP issues, legal issues, access to things like a Zoom account (specifically one of the things Express just asked for).  All of these things eat into a maintainers time away from the project.  While "more contributors" also helps, **a single maintainer can scale alright if they have support on these other things**.

> would it be wise to have a neutral person/account with owner-level access?

I think this should be a requirement.  If not a "person" but a "foundation managed account" which would only be used in an emergency.  For example, if on Express there was a security issue and Doug was unavailable, we would be in a tough position.  I have been working with him to plan to open it up, but for some projects it might not make sense to give every contributor the ability to push/publish.

> For example many very popular projects are effectively one person's passion who does most of the actual commits and that person not be easily replaceable (Be it due to time/priority/domain expertise/interest) even if there are other "active maintainers".

I think this is exactly the type of project which would gain the most from the foundation.  Judging a project based on number of contributors is, IMO, a great way to miss out on value.  Project impact and something clear to be gained by the project seem to me to be much better "criteria" and taking focus away from that is just a distraction IMO.

**Comment by mcollina** [comment]
I'm closing this issue, as we are not in aggreeement.
