### ISSUE TITLE
Request for legal Advice

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#335]
Based on the discussion in a recent pacakage-maintenance meeting on https://github.com/nodejs/package-maintenance/pull/255

The comment was

`I noticed the current draft of the support format uses "best effort", a problematic legalism common in contracts that's usually taken to mean rather the opposite of what the group seems to mean here. I recommend replacing "best effort" with something else`

We wanted to ask for advice from the legal committee on the suggested alternatives to `best-effort` and if this is an issue that we should be concerned with.

The options being considered include:

* ad-hoc --> put an approve (sorry there is only 8 emoji for comments)
* as-available 👍
* no-commitment 👎
* no-sla 😄
* good-intentions 🎉
* try-hard 😕
* willing ❤
* open 🚀
* time-permitting 👀

With `time-permitting` being the leading candidate.

**Comment by mhdawson** [comment]
@brianwarner can you please take this to the committee to get some advice?

**Comment by Trott** [comment]
ETOOMANYOPTIONS

**Comment by brianwarner** [comment]
I can certainly do so, but I'd also note that this isn't a term in a legal document.  There's always a balance between asking attorneys for answers and incurring billable hours, as well...

With this in mind, I might suggest first narrowing this down to the choice that makes the most sense in the context?  If there are still outstanding concerns at that point, I can help formulate a specific, scoped question so that we get back a specific, scoped answer.

**Comment by wesleytodd** [comment]
The issue was brought up by an attorney (@kemitchell), so I think we can be sure that it is important despite it not being in a "legal document".

>  I might suggest first narrowing this down to the choice

I think this has been done by the WG to `time-permitting` and `as-available`.  If the conversation was scoped just to those to in opposition to the original proposal of `best-effort` it would satisfy the concern I think.

**Comment by mhdawson** [comment]
I'm +1 on going back with `time-permitting` and `as-available` unless anybody objections to that?

**Comment by knolleary** [comment]
> `time-permitting` and `as-available`

+1

**Comment by mcollina** [comment]
+1

Il giorno gio 26 set 2019 alle 22:11 knolleary <notifications@github.com>
ha scritto:

**Comment by brianwarner** [comment]
As discussed on the CPC call, this particular situation is a case where legal would not typically get involved, and it's up to the project as to which term is most appropriate.

As a broader point, when unsure whether something needs legal review, definitely feel empowered to ask (as was done here).  This can either be done as an issue or, if one feels it is sensitive, by direct email.  I have an action to set up a mailing list to receive such questions, which I'll do shortly.  If you're not comfortable with that, you can always ask Foundation staff directly (operations@openjsf.org) and we'll route things appropriately.

**Comment by mhdawson** [comment]
My understanding was that guidance was that this is something that does not need legal review and the  package-maintenance team should feel free to chose which ever they feel is best.
