### ISSUE TITLE
Clarify IP assignment and transfer requirements in onboarding checklist

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#378]
The onboarding checklist is very vague about the assignment and transfer requirements of intellectual property from the project's IP owners to the foundation.

It would be good to clarify that, and maybe even include the point person responsible for handling this on the foundation's side if at all possible.

**Comment by brianwarner** [comment]
Good point, I can be the point person (but please use operations@openjsf.org for the contact).

**Comment by tobie** [comment]
On this topic, when does the IP assignment and transfer actually happen? Given the CPC has to approve a project graduating from incubation, I imagine the IP assignment and transfer is somehow conditional to the CPC's approval. How does that work in practice?

**Comment by keywordnew** [comment]
ESLint (an At-Large project) is [waiting guidance from the Foundation](https://github.com/eslint/website/pull/712#issuecomment-613043591) on the subject of intellectual property rights. 

The project was part of the JS Foundation pre-merger. I'm unclear about whether to create a new Issue. The topic for ESLint seems to be about transferring IP from the predecessor Foundation, rather than from the project owners. If it's not really within the scope of this, #386, let me know, then I'll create a new one.

Thanks folks 🙏🏽

**Comment by brianwarner** [comment]
Thanks @keywordnew , I responded on the other thread.  That change looked fine, and you might want to consider using this opportunity to update the footer with the standard footer approved by the Board: https://github.com/brianwarner/cross-project-council/blob/add-copyright-policy/IP-POLICY-GUIDANCE.md#copyright-notices-for-website-footers

**Comment by keywordnew** [comment]
Thank you, @brianwarner 👏🏽 Moving back there to continue resolution.
