### ISSUE TITLE
Should we remove 3 month requirement in foundations projects for potential regular members?

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#446]
Per our [charter](https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#regular-members) to become a regular member of the Cross Project Council, you need to be active in a foundation project for at least three months.

We may be limiting engagement and involvement from otherwise enthusiastic members of our community with this restriction.

Perhaps we remove or lower that restriction or tweak it in some other way to lower the bar in an effort to provide greater access to our work from people who are interested in getting involved.

I've brought this up in passing a number of times and @MylesBorins raised it in recently as well.

What are people's thoughts? Thanks! 🙌

**Comment by ljharb** [comment]
What was the motivation behind the 3 month requirement in the first place?

My assumption is that it's to be sure that people who have influence over the entire foundation, have at least enough context to speak knowledgeably about one of the projects.

**Comment by mhdawson** [comment]
@joesepi it might be useful to share some specifics in terms of people who have not been able to nominate themselves (possibly privately) to add to the context.

I'm not aware of a case where its been a problem but would like to understand better.

As @ljharb noted the requirement was so that people had some context, track record of contributing to the projects.

People without that can still participate as observers, comment in the issues etc.  The only real limitation is in terms being org owners and in cases when we don't reach concensus.  I don't remember specific cases where this would have made a practical different in terms of individuals being able to participate other than not being included in the private section of CPC meetings. Even in those cases I think people who were asked to leave could have been regular CPC members, they just had not requested to join yet.

**Comment by joesepi** [comment]
I agree @mhdawson. I think we can address this when we have real use cases that are limited by this requirement.

For context into my thinking: I am trying to get new people involved in both the Node.js work and the OpenJS work. It feels like that 3 month requirement could be a limiting barrier, but I haven't found that yet. I will still work to encourage "outsiders" (to projects) to get involved and will monitor how things go.

**Comment by mcollina** [comment]
The way the CPC is set up means that _everybody_ can join and partecipate in the decision seeking process. Being a member matters for some of the more critical function of the CPC, and I think 3 months provide enough context of their original project to begin with.

**Comment by joesepi** [comment]
Closing until this is an actual barrier and then we can discuss further if we see fit.
