### ISSUE TITLE
Opening nominations for the next year's voting CPC members

### ISSUE THREAD

**Issue by eemeli** [openjs-foundation/cross-project-council#472]
As mentioned in [our governance document](https://github.com/openjs-foundation/cross-project-council/blob/master/GOVERNANCE.md#term-for-voting-members), the term for all voting members of the CPC is ending on 31 March 2020, and new members need to be selected before then.

For impact projects, next year's members need to be nominated (or re-nominated) by each project, and then ratified by the CPC.

For non-impact projects, this means that we need to elect the two representatives. This [election process](https://github.com/openjs-foundation/cross-project-council/blob/master/GOVERNANCE.md#election-process-for-non-impact-voting-cpc-members) specifies that a two-week nomination period precedes this election, which means that this ought to start Real Soon Now.

To clarify, this issue is not the issue officially announcing the opening of the nomination period.

**Comment by boneskull** [comment]
Am I right that we're going to need to shed some voting members?

**Comment by mhdawson** [comment]
@boneskull I think the answer is yes. Last year we agreed to add all who applied but the governance states that there are only 2 voting CPC members from the non-impact projects: https://github.com/openjs-foundation/cross-project-council/blob/master/GOVERNANCE.md#election-process-for-non-impact-voting-cpc-members

We of course can propose changes, but I'm thinking we might cut down on which roles need to be filled by voting members (ex Chair and Board representative) instead so that there is a lower impact on having regular members versus voting members in terms of candidates.  The other option we have which we have not exercised is having the voting members elect 2 of the regular members to be voting members.

**Comment by jorydotcom** [comment]
Opened #488 per our discussion here, in the meetings & on the slack channel

**Comment by eemeli** [comment]
Closing as resolved. :)
