### ISSUE TITLE
Add sponsor logos for companies donating employee time

### ISSUE THREAD

**Issue by timmywil** [openjs-foundation/cross-project-council#525]
This issue is for discussing adding a place on the openjs website to add company logos for contributors who might like to give recognition to their employers for donating some time to work on OpenJS projects. It may or may not live in the same place as similar pages for memberships or donations.

It came up recently on the jQuery team. I considered adding a page on the jQuery site just for us, but right now it would only include 1 or 2 companies. I thought there could perhaps be a more central place.

**Comment by ljharb** [comment]
Presumably the time has a monetary value in terms of taxes, and could be documented as an actual donation? At that point I'd expect it to be treated equivalently to someone writing a check.

**Comment by MylesBorins** [comment]
So the OpenJS foundation is a 501(c)6 and [as per the IRC](https://www.irs.gov/charities-non-profits/other-non-profits/tax-treatment-of-donations-501c6-organizations)

> Contributions to section 501(c)(6) organizations are not deductible as charitable contributions on the donor’s federal income tax return. They may be deductible as trade or business expenses if ordi­nary and necessary in the conduct of the taxpayer’s business. The donee organization may be required to make certain disclosures and pay a proxy tax in connection with the dues payment, however.

Calling something a donation, even in-kind, does have potential ramifications for membership in the foundation.

From a marketing perspective many large companies want to be a part of the conversation about where their mark is being used, and may not actually be happy that an individual employee has included their brand no-matter how generous offering to do so is.

I'll admit that as a member of the foundation I likely have bias here, but I really don't think that we should be putting company logos on the site that are not members of the foundation. If we want to offer a membership level that is associated with measured in-kind donations that would be a request for us to make to the board.

FWIW we have a thank you at the bottom of https://nodejs.org/ for contributors which I think is a very nice thing to do, so I'm not totally opposed to this.

**Comment by brianwarner** [comment]
+1 to what Myles said, and to provide a little context... membership is currently structured the way that it is because it's really hard to measure in-kind contributions.  For this reason there really isn't a mechanism for evaluating whether an in-kind contribution is equivalent to formal membership.

That said, it's a great idea to thank your contributors, and putting logos up on the website on a "thank you for your contributions" page (with permission, ideally PR'd by a rep from the org itself) is a great way to do this.

**Comment by timmywil** [comment]
I know it's been a while, but wanted to pick this up again. I think we have some agreement about a contributions page that is separate from memberships, so the resolution would be the creation of that page.

**Comment by MylesBorins** [comment]
@timmywil it might make sense to update the Title of this post.

One question that I'm wondering. Are you looking for:

1. guidance on how a project can in good faith thank contributors
2. An official place on the openjsf website or the cpc repo to thank companies

I'll be honest, I'm not super bullish on the idea of thanking companies for giving employees time to work on foundation projects. I can't really think of a decent measuring system or threshold that would make it appropriate to thank a company... and also could see companies taking advantage of something like this and pressuring employees to get their names included, even if they are not actively working on company time.

Since there isn't a great way to measure this and ensure fairness... I'm not sure it is the best idea. Thanking contributors for their time and mentioning their employment (at the request of the collaborator) seems like a fairer way to handle this... but tbh it makes a lot more sense at the project level rather than foundation level.

The cost of entry for a silver membership (included below) is not a massive amount of money, and is a clear path to companies getting recognition. I'm also concerned that giving broader recognition for employee contribution would undermine one of the values of this level of membership

```
Over 2,000 employees: $25k
500 to 2,000 employees: $15k
100 to 499 employees: $10k
Under 100 employees: $5k
```

**Comment by timmywil** [comment]
I'm mostly looking for #2. I think we can do it in a way that makes it clear that it is separate from memberships. A central place to collect logos for these sorts of companies made sense to me because the jQuery core team by itself wouldn't have very many to show on a page on its own.

**Comment by MylesBorins** [comment]
@timmywil I'll let others chime in here, but I'm not very enthusiastic about having a list like this. It would be hard to set an appropriate bar for entry, hard to determine a bar for being removed, and would require a decent amount of maintenance to keep up to date.

**Comment by eemeli** [comment]
I agree with @MylesBorins here. I don't think we could come up with a universally applicable bar for entry on this, other than "anything goes", and that would cheapen both us and any value of such a page.

Admittedly it would be cool to be able to gather a ranking of companies according to how much developer time they're contributing to OpenJS projects, but not really cool enough to be worth the hassle and effort.

**Comment by tobie** [comment]
Should we close this?

**Comment by timmywil** [comment]
I suppose so
