### ISSUE TITLE
Project charter review for AMP

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#552]
AMP is getting closer to completing its [onboarding checklist](https://github.com/openjs-foundation/project-onboarding/issues/24). (For those of you who are interested, progress on the various items are tracked in a [dedicated project board](https://github.com/orgs/ampproject/projects/4).)

AMP Charter is now ready to be reviewed by the CPC.

It currently sits as a pull request in AMP's meta repository: https://github.com/ampproject/meta/pull/56 and we'd appreciate the CPC's review.

As a result of the new requirements added by the CPC, please also review the related pull request to GOVERNANCE.md: ampproject/meta#55.

**Comment by mhdawson** [comment]
The content of the charter + GOVERNANCE.md look good to me.

I think though that to be consistent with what's been subject to review by the CPC/and possibly Board in the past changes to both the CHARTER.md and GOVERNANCE.md would need approval by the CPC. If its ok to update the char CHARTER.md to indicated that changes to both doc's require approval then that would be the only change necessary. 

Otherwise it probably needs a deeper discussion of what needs review/approval by the CPC/possibly board because if it's only the charter.md as written that would need approval as written then the CPC has a review/signoff on effectively almost nothing.

**Comment by eemeli** [comment]
Looks pretty good. My only concerns are the way that the single-employer limits are phrased in the governance doc:
> No more than ⅓ of the Advisory Committee should be from one employer.

> The TSC shall have a goal of having no more than ⅓ of the TSC from one employer. Given the requirement that membership in the TSC requires recognized technical and/or product experience with AMP this may not be feasible at the time the TSC is formed, but the TSC should actively work towards this goal.

Is the limit for the AC a hard limit, or is that too aspirational? If it's meant to be a hard limit, using "must" or "may" instead of "should" would make that clearer.

To be clear, I'm happy to +1 this, just find these expressions a bit... fuzzy.

**Comment by tobie** [comment]
As a result of the new requirements added in today's CPC call, please also approve the related pull request to GOVERNANCE.md: https://github.com/ampproject/meta/pull/55

**Comment by tobie** [comment]
@eemeli wrote:
> To be clear, I'm happy to +1 this, just find these expressions a bit... fuzzy.

Thanks for your comment, @eemeli. With my standards background, I read this as RFC 2119 language which [defines](https://tools.ietf.org/html/rfc2119#section-3) "should" as:

> This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.

For context, the TSC is slightly unbalanced right now but is actively working towards achieving this goal. I think we should revisit this wording when the project attempts to graduate from Growth to Impact. Would that work for you?

**Comment by tobie** [comment]
@joesepi & @mhdawson: I made the requested changes to the charter. I'm additionally requesting review of the related changes to governance.md in (ampproject/meta#55) as now required.

**Comment by mhdawson** [comment]
+1

**Comment by joesepi** [comment]
+1 for approving charter/governance in the current form

**Comment by joesepi** [comment]
Two approvals. No objections. Good to go.
