### ISSUE TITLE
Criteria to move to Emeritus

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#713]
PEP recently moved to Emeritus without any vote. Project Progression says there should be a vote. If we do not believe there should be a vote, then we should update Project Progression.

https://github.com/openjs-foundation/cross-project-council/blob/main/PROJECT_PROGRESSION.md#acceptance-criteria-3

Let's discuss. :)

**Comment by ljharb** [comment]
It seems like others should be given the opportunity to continue the work first - for example, in this case, if someone wanted to take over maintenance of the project because they still support IE 10, it would seem cleaner to do that than to have them fork it.

That said, if there’s consensus that a project is no longer useful, and no maintainers willing to maintain it, it doesn’t seem like we should be able to vote *against* moving it to emeritus status.

**Comment by boneskull** [comment]
I think it makes sense to allow projects to move into emeritus at their discretion.  Just because it has moved into emeritus does not mean someone _cannot_ still maintain it, even if it is considered abandoned by the OJSF.  Even if it's an _impact_ project, it's possible that an existing project's leadership decides to abandon it and move to emeritus.  

If work on such a project _were_ to be taken over by new leadership, it'd behoove us to re-evaluate the project status and its place in the foundation anyway (note: there is nothing in project progression mentioning a move from emeritus to a different stage; IMO we can evaluate that if/when it ever occurs, and collaborate on a process at that time--it's probably not worth worrying about right now).

The CPC should still retain the right to move a project into emeritus via vote if project ownership is unresponsive or unreachable.

**Comment by eemeli** [comment]
Maybe it would be beneficial to alter the wording to talk more about consensus, rather than a vote, for a project that does have leadership that wishes to change its status to emeritus? That would more close match our process for accepting projects into incubation.

```diff
 #### Acceptance Criteria

-Projects may be granted Emeritus status via a 2/3 vote from the CPC and with approval from project ownership.
-In cases where there is a lack of project ownership, only a 2/3 vote from the CPC is required.
+Projects may be granted Emeritus status with the consent of the CPC and with approval from project ownership.
+In cases where there is a lack of project ownership, a 2/3 vote from the CPC is required.
```
