### ISSUE TITLE
Welcome VoltrexMaster to the CPC as a Regular Member

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#875]
Welcome!

I've added you to the regular members list: https://github.com/orgs/openjs-foundation/teams/cpc-regular-members/members

Let's introduce you or at least announce your new membership at the next CPC meeting.

We are happy to have you get involved. If you have any questions or comments, please reach out via Github or through Slack. You can find all sorts of contributing resources at https://openjsf.org/collaborate

Cheers!

**Comment by joesepi** [comment]
Reference: https://github.com/openjs-foundation/cross-project-council/pull/861

**Comment by VoltrexMaster** [comment]
Thank you for adding me as a regular member! It's an honor and I'm happy to be involved.

I only have one question about all of this, is attending to the CPC meetings (the ones on Zoom or wherever) mandatory? i'm asking this because I'm not comfortable with attending to meetings where I have to show my face or similar, if so is there a way to discuss these via text instead of video chat and similar?

**Comment by ljharb** [comment]
You're not required to have your video on, but it's encouraged. Things are discussed with text in Slack and on Github, but decisions are made in the face-to-face meetings.

**Comment by joesepi** [comment]
Welcomed in today's meeting!

@VoltrexMaster - there are many ways to contribute to OpenJS and the CPC. The meetings are not required but we would be happy to have you join in the conversation. You can always keep your video off -- no pressure there whatsoever. However, if you would prefer to help in issues, pull requests, documentation and the like, that is also fine.

At the following URL, you will find links to our Slack, calendar and other ways to collaborate. Cheers!
https://openjsf.org/collaborate
